### ISSUE TITLE
Xcode 6.3

### ISSUE THREAD

**Issue by f33chobits** [neonichu/BBUDebuggerTuckAway#17]
Not working on Xcode6.3  
OS 10.10.3
Swift project

**Comment by thejackz** [comment]
Not working for me as well. 
OS 10.10.3
C project

**Comment by thedp** [comment]
Same here.
XCode 6.3.1
OS X Yosemite 10.10.2

**Comment by rrecio** [comment]
Same here

**Comment by neonichu** [comment]
We need the new UUIDs in the Info.plist, similar to this commit 1f30ba92cb11361e8bc9e29454f14890fcd63e2a - don't have time right now to update all the plugins, so would love if someone could make a PR.

**Comment by neonichu** [comment]
Fixed by #18
