### ISSUE TITLE
Strange in xCode 6.4

### ISSUE THREAD

**Issue by trialabc** [neonichu/BBUDebuggerTuckAway#21]
I have installed xcode 6.4 and with alcatraz plugin. 
I install the BBUDebuggerTuckAway through the "package manager". It works properly at first clean install. 
However, after I have closed xcode, and restarted it again. It seems that this plugin is no longer installed or loaded.
It would be great if it works again so that I do not need to reinstall over and over again.

**Comment by neonichu** [comment]
Strange that it sometimes worked, the plugin was missing the 6.4 release compatibility UUID. Maybe that was actually a bug in Xcode's new plugin loading mechanism :)

Anyways, 36b1c1b205696268faee374801eef4caf1383ebe added the compatibility UUID which should fix this.
